// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_mira_antes_de_cruzar = "CgkIpMLIoLcZEAIQAw"; // <GPGSID>
        public const string achievement_recoge_100_frutas = "CgkIpMLIoLcZEAIQBg"; // <GPGSID>
        public const string leaderboard_mejores_puntuaciones = "CgkIpMLIoLcZEAIQCA"; // <GPGSID>
        public const string achievement_tu_primera_fruta = "CgkIpMLIoLcZEAIQAQ"; // <GPGSID>
        public const string achievement_cuidado_con_los_trineos = "CgkIpMLIoLcZEAIQBQ"; // <GPGSID>
        public const string achievement_la_has_palmado = "CgkIpMLIoLcZEAIQAg"; // <GPGSID>
        public const string achievement_salta_100_troncos = "CgkIpMLIoLcZEAIQBw"; // <GPGSID>
        public const string achievement_espero_que_sepas_nadar = "CgkIpMLIoLcZEAIQBA"; // <GPGSID>

}

